export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	DELETE_TODO: 'DELETE_TODO_IN_TODOS',
	UPDATE_TODO: 'UPDATE_TODO_IN_TODOS',
	CREATE_TODO: 'CREATE_NEW_TODO_IN_TODOS',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	SET_IS_LOADING: 'SET_IS_LOADING',
	SET_IS_UPDATING: 'SET_IS_UPDATING',
	SET_IS_CREATING: 'SET_IS_CREATING',
	SET_IS_SORTING: 'SET_IS_SORTING',
	SET_EDITING_TODO_ID: 'SET_EDITING_TITLE_TODO_ID',
	SET_ERROR: 'SET_ERROR',
};
